### ISSUE TITLE
Send keys are opening the window

### ISSUE THREAD

**Issue by crackcomm** [knq/chromedp#48] opened 2017-03-28 02:59 UTC
On `SendKeys` the window is focused.
Is it possible to fix it? It's impossible to bear, headless chrome doesn't work with SOCKS proxy (does it?).

**Comment by kenshaw** [comment] 2017-03-28 03:02
`headless_shell` and Chrome headless (ie `--headless`) both work fine with SOCKS proxies. When you say the Window is focused, do you mean that if you have the launched Chrome window minimized, it keeps coming to the front? If so, that's likely by design on Chrome.

**Comment by crackcomm** [comment] 2017-03-28 03:16
How to set a proxy with `headless_shell` in a Docker container?

**Comment by kenshaw** [comment] 2017-03-28 03:17
Modify the `Dockerfile`, rebuild the image.

**Comment by crackcomm** [comment] 2017-03-28 03:19
I tried to set `--proxy-address` flag in `headless_shell` but it doesn't accept `socks5://…` address.

```
[0328/020721.382151:ERROR:headless_shell.cc(484)] Malformed proxy server url
```

**Comment by kenshaw** [comment] 2017-03-28 03:21
I believe it's `--proxy-server` -- http://peter.sh/experiments/chromium-command-line-switches/

**Comment by crackcomm** [comment] 2017-03-28 03:24
Yes, that's what I meant, sorry.

**Comment by kenshaw** [comment] 2017-03-28 03:25
Try without the protocol -- just 'localhost:5000' or whatever ... Alternatively, use regular Chrome.

**Comment by kenshaw** [comment] 2017-03-28 03:27
By "without the protocol" I mean without the `scheme://` component of the URL -- ie, drop `socks://`. `headless_shell` does not seem to support command line options "exactly the same" as Chrome. However, `headless_shell` really is just a stripped down version of Chrome. If you use a version of Chrome that supports `--headless` you'll get the same thing as what `headless_shell` is, but will be the full version of Chrome (at least from my understanding of the relationship between Chrome/headless_shell/other chrome based apps...).

**Comment by crackcomm** [comment] 2017-03-28 03:29
I tried it also and it just doesn't use proxy then. I think it's a known issue with `headless_shell`.
When I set `Flag("headleass", true)` this is what I've got:

```
$ time go run main.go
2017/03/28 05:29:21 timeout waiting for initial target
exit status 1
go run main.go  1.60s user 0.24s system 42% cpu 4.384 total
```

**Comment by kenshaw** [comment] 2017-03-28 03:32
You might want to check / ensure that `--remote-debugging-port` is being passed to Chrome properly, when using with `--headless`.

**Comment by crackcomm** [comment] 2017-03-28 03:33
It is indeed `--remote-debugging-port=9222`.

**Comment by kenshaw** [comment] 2017-03-28 03:35
Using it headless is tricky, in general. You should check what the actual "display" looks like by connecting directly, and see if your proxy settings are working properly, by trying to browse out to a website via the proxy.

**Comment by crackcomm** [comment] 2017-03-28 03:40
The proxy works fine when not using headless in a Docker container.

**Comment by kenshaw** [comment] 2017-03-28 03:45
Oh? Perhaps its just the version of the `headless_shell` then? Regardless, if the `--proxy-*` parameters to Chrome aren't working, that's not really a `chromedp` issue -- closing.

**Closed by kenshaw** 2017-03-28 03:45 UTC

**Comment by crackcomm** [comment] 2017-03-28 03:57
Actually the issue still remains it's the discussion that got off topic.
I am starting chrome not maximized and on `SendKeys` it gets focused, is it possible to fix?

**Comment by kenshaw** [comment] 2017-03-28 04:02
`chromedp` has nothing to do with system level window management. If Chrome is becoming focused, that's because Chrome is doing it. I am not aware of any Chrome Debugging Protocol APIs that would stop/prevent that from happening. As such, whether or not the `--proxy-*` or the windowing aspects are working as expected, that needs to be handled / fixed in the Chromium source, as it's not something that can be fixed (as far as I'm aware)/driven from the chrome debugging protocol. Perhaps its a command line option? Should check what happens in Selenium. If it happens the same way with Selenium, then its likely "not fixable" via this package. If Selenium does it differently, then it's most likely due to a passed parameter when launching Chrome. I'd gladly make that one of the defaults, but I'm not able to go through the Selenium/ChromeDriver code at the moment to determine if the behavior is different there.

**Comment by crackcomm** [comment] 2017-03-28 04:05
Thanks @kenshaw. Selenium `chromedriver` doesn't focus windows but I am not aware of command line parameters it passes to chrome.

But most strange thing is – it only does it sometimes so this indicates that it might indeed be unfixable in chromedp.

Thanks anyway.

**Comment by kenshaw** [comment] 2017-03-28 04:09
If you can find out what's happening with ChromeDriver, I'd gladly integrate whatever changes need to be done. Please note that `chromedriver` itself is actually a special app; and calls internally to the various C++ components of Chrome. I don't think it drives Chrome through the debugging protocol in the same way that `chromedp` does. I haven't messed/tried it yet with the `chromedp-proxy` tool I wrote, but you might want to give it a try and see if magically there are undocumented features or some such. Also, it'd be helpful to just capture the command line options passed to Chrome from `chromedriver`.

**Comment by crackcomm** [comment] 2017-03-28 04:21
Well but it doesn't seem right to me that it does it maybe 50% of times.
I now identified a consistent pattern, it does it only when previously chrome was manually browsed (and chromedp was doing nothing then).

**Comment by kenshaw** [comment] 2017-03-28 04:24
Ok ... that doesn't make much sense to me -- but if it does have different behavior after/before you've "touched" the window, then that is definitely not an issue with `chromedp`. The various actions packaged in `chromedp` just map to the low level Chrome Debugging Protocol domain APIs. `chromedp` on its own, doesn't really do anything, other than provide a convenient way to organize the data sent/received from to/from the CDP. All the real work is done by Chrome ...

**Comment by crackcomm** [comment] 2017-03-28 04:26
Thanks for your time @kenshaw. It seems that it can't be fixed without really deep digging into Chrome source code so I'll just ignore that and move to headless if needed. Thanks again.

**Comment by crackcomm** [comment] 2017-03-28 23:23
In case someone stumbles upon issues with running Chrome `--headless` or `headless_shell` it just works to run `xvfb-run --server-args='-screen 0, 1024x768x16' go run main.go`.
