### ISSUE TITLE
Headless, timeout waiting for initial target

### ISSUE THREAD

**Issue by Unlym** [knq/chromedp#153] opened 2017-12-11 08:43 UTC
Hi, 

```
        var options cdp.Option
	options = cdp.WithRunnerOptions(
			runner.Headless(pathBrowser, 9222),
			runner.Flag("headless", true),
			runner.Flag("disable-gpu", true),
		)
	
	chrome, err := cdp.New(ctxt, options)
	if err != nil {
		log.Fatal(err)
	}
```

On a server without UI (Ubuntu 16.04), everything worked two weeks ago, when the chromium up to version 62, the service returns an error

`2017/12/11 10:35:00 timeout waiting for initial target`

And on the local computer  (Ubuntu 16.04) everything works

What can be the problem?

**Comment by Unlym** [comment] 2017-12-12 11:52
I solved this problem. Script started from user 'root' on server. 
Need to add flag ` "no-sandbox", true `  and everything works

**Comment by kenshaw** [comment] 2017-12-18 04:01
Yes, typically disabling the sandbox will cause Headless to run much much faster. The issue is that the current timeouts (everywhere in the source) are hard coded. You can change the default value locally if you need to, for now. An updated version of `chromedp` will be released soon, that will provide options to change the default timeout values.

**Closed by kenshaw** 2017-12-18 04:01 UTC

**Comment by wuze** [comment] 2018-12-20 01:00
I think you should use chrome 68,for I  reproduce this problem on chrome 70,
